### ISSUE TITLE
multiple hdds and virtual drives

### ISSUE THREAD

**Issue by Xyz00777** [petersulyok/smfc#61]
Hi i have a small problem...
when i execute install.sh than a new file conf is created (what is normal) BUT, its pasting not just one but multiple hdds inside the conf and it looks like its not compatible with it and additionaly it also pastes into the config nearly all other disks from the /dev/disk/by-id/ folder into it.

so i have two problems:
1. it looks like its not compatible with multiple hdds. Error:
```
Mar 17 22:39:18 ds9 smfc.py[1986363]: Traceback (most recent call last):
Mar 17 22:39:18 ds9 smfc.py[1986363]:   File "/opt/smfc/smfc.py", line 1169, in <module>
Mar 17 22:39:18 ds9 smfc.service[1986363]:    steps = 10
Mar 17 22:39:18 ds9 smfc.service[1986363]:    sensitivity = 3.0
Mar 17 22:39:18 ds9 smfc.py[1986363]:     service.run()
Mar 17 22:39:18 ds9 smfc.py[1986363]:   File "/opt/smfc/smfc.py", line 1144, in run
Mar 17 22:39:18 ds9 smfc.service[1986363]:    polling = 2.0
Mar 17 22:39:18 ds9 smfc.service[1986363]:    min_temp = 40.0
Mar 17 22:39:18 ds9 smfc.py[1986363]:     self.hd_zone = HdZone(self.log, self.ipmi, self.config)
Mar 17 22:39:18 ds9 smfc.py[1986363]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 17 22:39:18 ds9 smfc.py[1986363]:   File "/opt/smfc/smfc.py", line 742, in __init__
Mar 17 22:39:18 ds9 smfc.service[1986363]:    max_temp = 70.0
Mar 17 22:39:18 ds9 smfc.py[1986363]:     raise ValueError(f'Inconsistent count ({count}) and size of hd_names ({len(self.hd_device_names)})')
Mar 17 22:39:18 ds9 smfc.py[1986363]: ValueError: Inconsistent count (1) and size of hd_names (2)
Mar 17 22:39:18 ds9 smfc.service[1986363]:    min_level = 20
Mar 17 22:39:18 ds9 smfc.service[1986363]:    max_level = 100
Mar 17 22:39:18 ds9 smfc.service[1986363]:    hwmon_path = ['/sys/bus/pci/drivers/k10temp/0000:00:18.3/hwmon/hwmon9/temp1_input']
Mar 17 22:39:18 ds9 smfc.service[1986363]:    Temperature to level mapping:
Mar 17 22:39:18 ds9 smfc.service[1986363]:    0. [T:40.0C - L:20%]
Mar 17 22:39:18 ds9 smfc.service[1986363]:    1. [T:43.0C - L:28%]
Mar 17 22:39:18 ds9 smfc.service[1986363]:    2. [T:46.0C - L:36%]
Mar 17 22:39:18 ds9 smfc.service[1986363]:    3. [T:49.0C - L:44%]
Mar 17 22:39:18 ds9 smfc.service[1986363]:    4. [T:52.0C - L:52%]
Mar 17 22:39:18 ds9 smfc.service[1986363]:    5. [T:55.0C - L:60%]
Mar 17 22:39:18 ds9 smfc.service[1986363]:    6. [T:58.0C - L:68%]
Mar 17 22:39:18 ds9 smfc.service[1986363]:    7. [T:61.0C - L:76%]
Mar 17 22:39:18 ds9 smfc.service[1986363]:    8. [T:64.0C - L:84%]
Mar 17 22:39:18 ds9 smfc.service[1986363]:    9. [T:67.0C - L:92%]
Mar 17 22:39:18 ds9 smfc.service[1986363]:    10. [T:70.0C - L:100%]
Mar 17 22:39:22 ds9 smfc.service[1986363]: smfc terminated: all fans are switched back to the 100% speed.
```
2. it adds virtuall hdds which it shouldnt add per default...
![Image](https://github.com/user-attachments/assets/114cb098-533c-446f-8d63-a82925c79c5a)

Would it be possible to add an allow/deny list for formating what hdds are allowed/denied to be added to the config?

**Comment by petersulyok** [comment]
Hi @Xyz00777, thanks for reporting this.

Originally I added this feature to `install.sh` to make the creation of the initial configuration easier. Let me explain, we might have different expectations here.

When you create your initial config, it is a manual work to create `hd_names=` list with your HDD names from `/dev/disk/by-id` folder.
I thought that the process where `install.sh` adds all disk names to the config file then user deletes the unnecessary ones is easier than user collects all of them and writes them to the config manually.

Once you have your config file finalized, and you would like to update only the program itself with a later release, use this parameter:

`install.sh --keep-config`

and your configuration file will be preserved during installation.

> Would it be possible to add an allow/deny list for formating what hdds are allowed/denied to be added to the config?
Not sure how can we do that. We can filter out further duplicates from the list (e.g. `wnn-*`, *eui*).
Let me know if you have further ideas here.

Interesting fact that I also use Proxmox but my virtual drives are not visible in `/dev/disk/` folder. I have ZFS file system on my root partition.

**Comment by Xyz00777** [comment]
good to know the --keep-config switch, will have to look into how to implement it into my ansible script. because at the moment i have set it up, that it checks if an update is available and when yes than it redownload the repo, makes my edits, executes the install and than reedit the config file.
I also dont know when the virtual disks from proxmox came up but thats already some time ago when it started. i also have zfs below it. what file type are your vm disks? my are configured as raw, and i also see that proxmox is creating them not as a file but directly as a zfs volume, maybe because of that...

i see multiple possibilitys,
1. let the user have the capability to create a allow/deny list of multiple entrys with regex for hard drives to monitor
2. In general make it compatibel with multiple hdds and ignore if some devices dont have temperature values and take the highest (it looks for me like its not compatible at the moment, i also tried multiple formating ways)
3. edit the python to ignore the following lines after hdd_names until the next key value
4. you say that its not designed like that and you do nothing and i have to try to fix it somehow with my script :D (i hope not that way :D)

**Comment by petersulyok** [comment]
Do you prefer an automatic or manual process with user interactions?
Currently this line (55) creates the filtered list of disks:

`$(ls /dev/disk/by-id/|grep -v -E ".*-part.$"|grep -v -E ".*_1$")`

**Comment by Xyz00777** [comment]
hmmm wouldnt both be possible?

maybe for further understanding heres my current ansible script:

```
---
- name: Smfc install and config
  hosts: ds9
  become: true
  vars:
    repo_url: https://github.com/petersulyok/smfc
    repo_dest: /root/smfc/
  tasks:
    - name: Install git and ipmitool
      ansible.builtin.package:
        name:
          - git
          - ipmitool
        state: present
        update_cache: true

    - name: Ensure kernel modules for smfc are loaded
      ansible.builtin.lineinfile:
        dest: /etc/modules
        line: "{{ item }}"
      loop:
        - drivetemp
        - k10temp

    # --- Check local repo state ---
    - name: Check if the repository already exists
      ansible.builtin.stat:
        path: "{{ repo_dest }}/.git"
      register: repo_exists

    - name: Get current tag from the local repository
      ansible.builtin.command: git describe --tags
      args:
        chdir: "{{ repo_dest }}"
      register: local_version
      when: repo_exists.stat.exists
      changed_when: false

    - name: Set the local version or default value
      ansible.builtin.set_fact:
        local_version_tag: "{{ local_version.stdout.strip() | default('none') }}"
      when: repo_exists.stat.exists

    - name: Set default local version tag if repository does not exist
      ansible.builtin.set_fact:
        local_version_tag: none
      when: not repo_exists.stat.exists

    # --- Fetch latest release/tag from GitHub ---
    - name: Fetch latest release tag from GitHub
      ansible.builtin.uri:
        url: https://api.github.com/repos/petersulyok/smfc/releases/latest
        return_content: true
        status_code: 200
      register: github_tags_response

    - name: Set fact for latest tag
      ansible.builtin.set_fact:
        latest_tag: "{{ github_tags_response.json.tag_name }}"

    - name: Debug local vs. remote versions
      ansible.builtin.debug:
        msg:
          - "Local version: {{ local_version_tag }}"
          - "Remote version: {{ latest_tag }}"

    # If local version != latest tag, then clone or update
    - name: Determine if update is needed
      ansible.builtin.set_fact:
        update_needed: "{{ local_version_tag != latest_tag }}"

    - name: Clone or update the repository if a new version is available
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ latest_tag }}"
        force: true
      when: update_needed

    # --- Make IPMI config changes, then install smfc ---
    - name: Modify IPMI threshold script using dynamic regex
      notify:
        - Smfc service install
        - Stash local changes before pulling
        - Apply stashed changes
      block:
        - name: Replace lower threshold line dynamically
          ansible.builtin.replace:
            path: "{{ repo_dest }}/ipmi/set_ipmi_threshold.sh"
            regexp: for i in [0-9A-Z ]+;
            replace: for i in 1 2 3 4 5 A B;

        - name: Replace lower threshold values dynamically
          ansible.builtin.replace:
            path: "{{ repo_dest }}/ipmi/set_ipmi_threshold.sh"
            regexp: ipmitool sensor thresh FAN\${i} lower [0-9 ]+
            replace: ipmitool sensor thresh FAN${i} lower 0 500 700

        - name: Replace upper threshold values dynamically
          ansible.builtin.replace:
            path: "{{ repo_dest }}/ipmi/set_ipmi_threshold.sh"
            regexp: ipmitool sensor thresh FAN\${i} upper [0-9 ]+
            replace: ipmitool sensor thresh FAN${i} upper 1800 2000 2200

  handlers:
    - name: Smfc service install
      ansible.builtin.command: bash ./install.sh
      args:
        chdir: "{{ repo_dest }}"

    - name: Stash local changes before pulling
      ansible.builtin.command: git stash
      args:
        chdir: "{{ repo_dest }}"

    - name: Apply stashed changes
      ansible.builtin.command: git stash apply
      args:
        chdir: "{{ repo_dest }}"

- name: Smfc install and config
  hosts: ds9
  become: true
  tasks:
    - name: Modify configuration file for fan speed to temperature
      community.general.ini_file:
        path: /opt/smfc/smfc.conf
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      loop:
        - { section: Ipmi, option: swapped_zones, value: "1" }
        - { section: CPU zone, option: steps, value: "10" }
        - { section: CPU zone, option: min_temp, value: "40" }
        - { section: CPU zone, option: max_temp, value: "70" }
        - { section: CPU zone, option: min_level, value: "20" }
        - { section: CPU zone, option: hwmon_path, value: /sys/bus/pci/drivers/k10temp/0000*/hwmon/hwmon*/temp1_input }
        - { section: HD zone, option: steps, value: "10" }
        - { section: HD zone, option: min_temp, value: "30" }
        - { section: HD zone, option: max_temp, value: "70" }
        - { section: HD zone, option: min_level, value: "20" }
        - { section: HD zone, option: hd_names, value: /dev/disk/by-id/ata-ST18000NM000J-2TV103_ZR56B8VP }
      notify: Restart smfc service

  handlers:
    - name: Restart smfc service
      ansible.builtin.service:
        name: smfc
        state: started
        enabled: true

```

what am i doing:
1. ensure that the needed software and kernel modules are loaded
2. check the local and remote repo state
3. if a newer version tag is available remote(or none is available local), than its downloading the remote and overwrite the local source
4. than my threshold settings are getting placed, because it could be that you changed something in the config file and there could be new options available.
5. if there was a new repo version downloaded and changes done than the service get installed new, my smfc.conf options are getting placed in the configuration file and the service is getting restarted.

And yes im aware that i create every time a new conf file :D
Now back to your question. I dont really care about automatic/manual as long as the config key value syntax is correct i can handel it with ansible and regex. At the moment it looks for me, like its structured like an ini file but just named differently and based on the parser you are using its propably not compatible with multi line values https://en.wikipedia.org/wiki/INI_file
i have nothing against editing the config file manually and removing/adding the hard drives on my own but its not possible at the moment (as far as i know) because im not able to handel it with ansible because the other hard drives are in new lines which have no keys to serach with ansible.
I could edit the script so it searches for all lines with /dev/disk/by-id and throw all out and just add one drive back in, but this would be an workaround which would not like to do.

Is it even compatible with multiple hard drive temperatures at the moment? because it looks not like it would at the moment
