### ISSUE TITLE
Docker container fails to start on TrueNAS

### ISSUE THREAD

**Issue by psyspy1** [petersulyok/smfc#72]
Hello! I setup TrueNAS Scale on my NAS machine that has the SuperMicro H13SAE-MF motherboard. I tried running the docker CLI command and docker compose to start the smfc service. In both cases, the container just exits with code 6. The log is empty. Any idea on how to debug this issue?

**Comment by petersulyok** [comment]
Hi @psyspy1, 

Here are the program exit codes:

```
Program exit codes:
        0 - printing help or version text (argument parser)
        2 - invalid parameter (argument parser)
        5 - log system initialization error
        6 - config file error
        7 - runtime dependency error
        8 - IPMI initialization error
        9 - udev initialization error
        10 - none of the zones is enabled

```
Based on this check the host mapping of your config file.

**Comment by psyspy1** [comment]
Thank you. Here's my docker compose file:
```
services:
  smfc:
    image: petersulyok/smfc
    container_name: smfc
    network_mode: none
    logging:
        driver: journald
    privileged: true
    environment:
      - SMFC_ARGS=-l 3
      - PUID=568
      - PGID=568
    volumes:
      - /dev:/dev:ro
      - /run:/run:ro
      - /mnt/mypool/docker/local/smfc/smfc.conf:/etc/smfc/smfc.conf:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
```

Here's my `smfc.conf`:
```
#
#   smfc.conf (C) 2020-2025, Peter Sulyok
#   smfc 4.x service configuration parameters
#
#   Please read the documentation here: https://github.com/petersulyok/smfc
#

# Ipmi specific parameters.
[Ipmi]
# Path for ipmitool (str, default=/usr/bin/ipmitool)
command=/usr/bin/ipmitool 
# Delay time after changing IPMI fan mode (int, seconds, default=10)
fan_mode_delay=10
# Delay time after changing IPMI fan level (int, seconds, default=2)
fan_level_delay=2
# IPMI parameters for remote access (string, default='')
#remote_parameters=-U USERNAME -P PASSWORD -H HOST


# CPU zone: this fan controller works based on CPU(s) temperature.
[CPU zone]
# Fan controller enabled (bool, default=0)
enabled=1
# IPMI zone(s) (comma- or space-separated list of int, default=0))
ipmi_zone=0
# Calculation method for CPU temperatures (int, [0-minimum, 1-average, 2-maximum], default=1)
temp_calc=1
# Discrete steps in mapping of temperatures to fan level (int, default=6)
steps=6
# Threshold in temperature change before the fan controller reacts (float, C, default=3.0)
sensitivity=3.0
# Polling time interval for reading temperature (int, sec, default=2)
polling=2
# Minimum CPU temperature (float, C, default=30.0)
min_temp=30.0
# Maximum CPU temperature (float, C, default=60.0)
max_temp=70.0
# Minimum CPU fan level (int, %, default=35)
min_level=35
# Maximum CPU fan level (int, %, default=100)
max_level=100


# HD zone: this fan controller works based on HD(s) temperature.
[HD zone]
# Fan controller enabled (bool, default=0)
enabled=0

# GPU zone: this fan controller works based on GPU(s) temperature.
[GPU zone]
# Fan controller enabled (bool, default=0)
enabled=0
```
